/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AutomationsIndexRouteImport } from './routes/automations/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as RegisterSlugRouteImport } from './routes/register.$slug'
import { Route as AutomationsCadencesCadenceIdRouteImport } from './routes/automations/cadences/$cadenceId'
import { Route as AutomationsCadencesNewRouteImport } from './routes/automations/cadences/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSlugRoute = RegisterSlugRouteImport.update({
  id: '/register/$slug',
  path: '/register/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsCadencesCadenceIdRoute =
  AutomationsCadencesCadenceIdRouteImport.update({
    id: '/automations/cadences/$cadenceId',
    path: '/automations/cadences/$cadenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutomationsCadencesNewRoute = AutomationsCadencesNewRouteImport.update({
  id: '/automations/cadences/new',
  path: '/automations/cadences/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/automations/': typeof AutomationsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/automations/cadences/$cadenceId': typeof AutomationsCadencesCadenceIdRoute
  '/automations/cadences/new': typeof AutomationsCadencesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/automations': typeof AutomationsIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/events': typeof EventsIndexRoute
  '/automations/cadences/$cadenceId': typeof AutomationsCadencesCadenceIdRoute
  '/automations/cadences/new': typeof AutomationsCadencesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/automations/': typeof AutomationsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/automations/cadences/$cadenceId': typeof AutomationsCadencesCadenceIdRoute
  '/automations/cadences/new': typeof AutomationsCadencesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/pipeline'
    | '/products'
    | '/recovery'
    | '/settings'
    | '/tasks'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/events/$eventId'
    | '/register/$slug'
    | '/automations/'
    | '/companies/'
    | '/contacts/'
    | '/events/'
    | '/automations/cadences/$cadenceId'
    | '/automations/cadences/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/pipeline'
    | '/products'
    | '/recovery'
    | '/settings'
    | '/tasks'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/events/$eventId'
    | '/register/$slug'
    | '/automations'
    | '/companies'
    | '/contacts'
    | '/events'
    | '/automations/cadences/$cadenceId'
    | '/automations/cadences/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/pipeline'
    | '/products'
    | '/recovery'
    | '/settings'
    | '/tasks'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/events/$eventId'
    | '/register/$slug'
    | '/automations/'
    | '/companies/'
    | '/contacts/'
    | '/events/'
    | '/automations/cadences/$cadenceId'
    | '/automations/cadences/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PipelineRoute: typeof PipelineRoute
  ProductsRoute: typeof ProductsRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  RegisterSlugRoute: typeof RegisterSlugRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AutomationsCadencesCadenceIdRoute: typeof AutomationsCadencesCadenceIdRoute
  AutomationsCadencesNewRoute: typeof AutomationsCadencesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$slug': {
      id: '/register/$slug'
      path: '/register/$slug'
      fullPath: '/register/$slug'
      preLoaderRoute: typeof RegisterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/cadences/$cadenceId': {
      id: '/automations/cadences/$cadenceId'
      path: '/automations/cadences/$cadenceId'
      fullPath: '/automations/cadences/$cadenceId'
      preLoaderRoute: typeof AutomationsCadencesCadenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/cadences/new': {
      id: '/automations/cadences/new'
      path: '/automations/cadences/new'
      fullPath: '/automations/cadences/new'
      preLoaderRoute: typeof AutomationsCadencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PipelineRoute: PipelineRoute,
  ProductsRoute: ProductsRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  RegisterSlugRoute: RegisterSlugRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  AutomationsCadencesCadenceIdRoute: AutomationsCadencesCadenceIdRoute,
  AutomationsCadencesNewRoute: AutomationsCadencesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
